// Real sermon archive from the Mapleview Church Sermon Podcast RSS feed (podpoint.com/feed/5468).
// The feed exposes the ~100 most recent episodes. For the full 631-sermon archive back to 2014,
// request a full export from PodPoint and it can be merged in here.
export const SERMONS = [
  { title: "Marching Orders", passage: "Joshua 6:1-14", series: "Joshua", speaker: "Pastor Jon Bones", date: "Jul 5, 2026" },
  { title: "Whose Side Are You On?", passage: "Joshua 5:10-15", series: "Joshua", speaker: "Pastor Jon Bones", date: "Jun 28, 2026" },
  { title: "The Posture of Worship", passage: "Selected Passages", series: "Topical Studies", speaker: "Pastor Luke VanNortwick", date: "Jun 14, 2026" },
  { title: "Do It God's Way Now", passage: "Joshua 5:1-9", series: "Joshua", speaker: "Pastor Jon Bones", date: "Jun 7, 2026" },
  { title: "Stay on Target", passage: "Titus 3:9-15", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "May 31, 2026" },
  { title: "What Are These Stones?", passage: "Joshua 4:15-24", series: "Joshua", speaker: "Pastor Jon Bones", date: "May 24, 2026" },
  { title: "Remember to Remember", passage: "Joshua 4:1-14", series: "Joshua", speaker: "Pastor Jon Bones", date: "May 17, 2026" },
  { title: "Get Your Feet Wet", passage: "Joshua 3", series: "Joshua", speaker: "Pastor Jon Bones", date: "May 10, 2026" },
  { title: "Finding Grace in an Unexpected Place", passage: "Joshua 2", series: "Joshua", speaker: "Pastor Jon Bones", date: "May 3, 2026" },
  { title: "A Risk Worth Taking", passage: "Joshua 1:10-18", series: "Joshua", speaker: "Pastor Jon Bones", date: "Apr 26, 2026" },
  { title: "Strong and Courageous", passage: "Joshua 1:1-9", series: "Joshua", speaker: "Pastor Jon Bones", date: "Apr 19, 2026" },
  { title: "Introducing Joshua", passage: "Numbers 13-14", series: "Joshua", speaker: "Pastor Jon Bones", date: "Apr 12, 2026" },
  { title: "From the Grave to the Sky", passage: "Luke 24:36-53", series: "Luke", speaker: "Pastor Jon Bones", date: "Apr 5, 2026" },
  { title: "Church on Mission", passage: "Titus 3:1-8", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Apr 1, 2026" },
  { title: "The Best Bible Study Ever", passage: "Luke 24:13-35", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 22, 2026" },
  { title: "The Reality of the Resurrection", passage: "Luke 23:50-24:12", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 15, 2026" },
  { title: "Let There Be Dark", passage: "Luke 23:44-49", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 8, 2026" },
  { title: "3 Crosses, 2 Criminals, 1 Christ", passage: "Luke 23:32-43", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 1, 2026" },
  { title: "The Punch Line", passage: "Titus 2:11-15", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Feb 22, 2026" },
  { title: "A Blessed Inconvenience", passage: "Luke 23:26-31", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 15, 2026" },
  { title: "I Am Barabbas", passage: "Luke 23:1-25", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 8, 2026" },
  { title: "God in the Dock", passage: "Luke 22:63-71", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 1, 2026" },
  { title: "Judas and Peter", passage: "Luke 22:47-62", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 25, 2026" },
  { title: "Light the Beacon", passage: "Titus 2:1-10", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Jan 18, 2026" },
  { title: "No Other Way", passage: "Luke 22:39-46", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 11, 2026" },
  { title: "Same God, Different Methods", passage: "Luke 22:35-38", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 4, 2026" },
  { title: "The Gift in the Sift", passage: "Luke 22:21-34", series: "Luke", speaker: "Pastor Jon Bones", date: "Dec 28, 2025" },
  { title: "The Reason for Christmas", passage: "Galatians 4:4-5", series: "Christmas", speaker: "Pastor Jon Bones", date: "Dec 21, 2025" },
  { title: "Joseph, Father of Messiah", passage: "Selected Passages from Matthew and Luke", series: "Christmas", speaker: "Pastor Luke VanNortwick", date: "Dec 17, 2025" },
  { title: "Mary, Mother of Messiah", passage: "Luke 1:26-50", series: "Christmas", speaker: "Pastor Jon Bones", date: "Dec 7, 2025" },
  { title: "The Power of Forgiveness", passage: "Testimony", series: "Topical Studies", speaker: "Samuel Nehemiah", date: "Nov 30, 2025" },
  { title: "With You and For You", passage: "Luke 22:7-20", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 24, 2025" },
  { title: "The Enemy Within", passage: "Luke 22:1-6", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 16, 2025" },
  { title: "Fig-uratively Speaking", passage: "Luke 21:29-38", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 9, 2025" },
  { title: "It's a Jungle Out There", passage: "Titus 1:10-2:1", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Nov 2, 2025" },
  { title: "Lift Up Your Head: The King Is Coming!", passage: "Luke 21:5-28", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 26, 2025" },
  { title: "The Sum or the Sacrifice?", passage: "Luke 20:45-21:4", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 19, 2025" },
  { title: "God of the Living", passage: "Luke 20:27-44", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 12, 2025" },
  { title: "Render to Caesar, Surrender to God", passage: "Luke 20:19-26", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 5, 2025" },
  { title: "The Son, The Stone", passage: "Luke 20:9-18", series: "Luke", speaker: "Pastor Jon Bones", date: "Sep 28, 2025" },
  { title: "We Are Outsiders", passage: "Philippians 3:17-4:1", series: "Topical Studies", speaker: "Youth Director Matthew Fletscher", date: "Sep 22, 2025" },
  { title: "Persecuted for Righteousness Sake", passage: "Selected Passages", series: "Topical Studies", speaker: "Pastor Luke VanNortwick", date: "Sep 17, 2025" },
  { title: "Above Reproach", passage: "Titus 1:5-9", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Sep 14, 2025" },
  { title: "Who's In Charge Here?", passage: "Luke 19:45-20:8", series: "Luke", speaker: "Pastor Jon Bones", date: "Sep 7, 2025" },
  { title: "An Explosive Introduction", passage: "Titus 1:1-4", series: "Titus", speaker: "Pastor Luke VanNortwick", date: "Aug 31, 2025" },
  { title: "Final Q&A", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 28, 2025" },
  { title: "Eschatology", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 28, 2025" },
  { title: "All Roads Lead to Jerusalem", passage: "Luke 19:28-44", series: "Luke", speaker: "Pastor Jon Bones", date: "Aug 24, 2025" },
  { title: "Ecclesiology and Q&A", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 21, 2025" },
  { title: "Pneumatology", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 21, 2025" },
  { title: "Found Faithful", passage: "Luke 19:11-27", series: "Luke", speaker: "Pastor Jon Bones", date: "Aug 17, 2025" },
  { title: "Soteriology and Q&A", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 14, 2025" },
  { title: "Hamartiology", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 14, 2025" },
  { title: "God's Sovereignty in the Midst of Suffering", passage: "Genesis 50:18-20", series: "Topical Studies", speaker: "Youth Director Matthew Fletscher", date: "Aug 10, 2025" },
  { title: "Anthropology and Q&A", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 10, 2025" },
  { title: "Angels and Demons", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 9, 2025" },
  { title: "Christology and Q&A", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 8, 2025" },
  { title: "Theology Proper", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 7, 2025" },
  { title: "Bibliology", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 7, 2025" },
  { title: "Prolegomena", passage: "Theology 101", series: "Theology 101", speaker: "Pastor Luke VanNortwick", date: "Aug 6, 2025" },
  { title: "Shorty Gets Saved", passage: "Luke 19:1-10", series: "Luke", speaker: "Pastor Jon Bones", date: "Aug 3, 2025" },
  { title: "Wage War", passage: "Ephesians 6:10-24", series: "Ephesians", speaker: "Pastor Luke VanNortwick", date: "Jul 27, 2025" },
  { title: "JC in the OT", passage: "Luke 18:31-43", series: "Luke", speaker: "Pastor Jon Bones", date: "Jul 20, 2025" },
  { title: "Mission Impossible", passage: "Luke 18:18-30", series: "Luke", speaker: "Pastor Jon Bones", date: "Jul 13, 2025" },
  { title: "Kingdom Kids", passage: "Luke 18:15-17", series: "Luke", speaker: "Pastor Jon Bones", date: "Jul 6, 2025" },
  { title: "Jesus Loves Slaves!", passage: "Ephesians 6:1-9", series: "Ephesians", speaker: "Pastor Luke VanNortwick", date: "Jun 29, 2025" },
  { title: "Lord Have Mercy", passage: "Luke 18:9-14", series: "Luke", speaker: "Pastor Jon Bones", date: "Jun 22, 2025" },
  { title: "Faith That Won't Quit", passage: "Luke 18:1-8", series: "Luke", speaker: "Pastor Jon Bones", date: "Jun 15, 2025" },
  { title: "Waiting for Lightning to Strike", passage: "Luke 17:20-37", series: "Luke", speaker: "Pastor Jon Bones", date: "Jun 8, 2025" },
  { title: "1/10", passage: "Luke 17:11-19", series: "Luke", speaker: "Pastor Jon Bones", date: "Jun 1, 2025" },
  { title: "The Model of Marriage", passage: "Ephesians 5:22-33", series: "Ephesians", speaker: "Pastor Luke VanNortwick", date: "May 25, 2025" },
  { title: "I Am Second", passage: "Luke 17:7-10", series: "Luke", speaker: "Pastor Jon Bones", date: "May 18, 2025" },
  { title: "Millstones and Mulberry Trees", passage: "Luke 17:1-6", series: "Luke", speaker: "Pastor Jon Bones", date: "May 11, 2025" },
  { title: "The Rich Man's Regret", passage: "Luke 16:19-31", series: "Luke", speaker: "Pastor Jon Bones", date: "May 4, 2025" },
  { title: "Good News for Lawbreakers", passage: "Luke 16:14-18", series: "Luke", speaker: "Pastor Jon Bones", date: "Apr 27, 2025" },
  { title: "Resurrection Sunday 2025", passage: "John 19:38-20:18", series: "Topical Studies", speaker: "Pastor Jon Bones", date: "Apr 20, 2025" },
  { title: "Lessons from a Shady Servant", passage: "Luke 16:1-13", series: "Luke", speaker: "Pastor Jon Bones", date: "Apr 6, 2025" },
  { title: "The Spirit-Filled Life", passage: "Ephesians 5:15-21", series: "Ephesians", speaker: "Pastor Luke VanNortwick", date: "Mar 30, 2025" },
  { title: "Lost and Found, Part Four", passage: "Luke 15:21-32", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 23, 2025" },
  { title: "Lost and Found, Part Three", passage: "Luke 15:11-20", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 16, 2025" },
  { title: "Lost and Found, Part Two", passage: "Luke 15:8-10", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 9, 2025" },
  { title: "Lost and Found", passage: "Luke 15:1-7", series: "Luke", speaker: "Pastor Jon Bones", date: "Mar 2, 2025" },
  { title: "Radical Light Walkers", passage: "Ephesians 5:1-14", series: "Ephesians", speaker: "Pastor Luke VanNortwick", date: "Feb 23, 2025" },
  { title: "The Cost of Discipleship", passage: "Luke 14:25-35", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 16, 2025" },
  { title: "Dinner's Ready!", passage: "Luke 14:12-24", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 9, 2025" },
  { title: "Beware the Snare", passage: "Luke 14:1-11", series: "Luke", speaker: "Pastor Jon Bones", date: "Feb 2, 2025" },
  { title: "What Did the Fox Say?", passage: "Luke 13:31-35", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 26, 2025" },
  { title: "The Scrub Brush Kingdom", passage: "Luke 13:18-30", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 19, 2025" },
  { title: "Eighteen Long Years", passage: "Luke 13:10-17", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 12, 2025" },
  { title: "Ready to Meet Your Maker", passage: "Luke 13:1-9", series: "Luke", speaker: "Pastor Jon Bones", date: "Jan 5, 2025" },
  { title: "Two Kings, Three Responses", passage: "Matthew 2:1-18", series: "Christmas", speaker: "Pastor Jon Bones", date: "Dec 22, 2024" },
  { title: "A Son Will Be Given", passage: "Isaiah 7:1-14, 9:1-7", series: "Christmas", speaker: "Pastor Jon Bones", date: "Dec 15, 2024" },
  { title: "The Oldest Prophecy", passage: "Genesis 3:14-15", series: "Christmas", speaker: "Pastor Luke VanNortwick", date: "Dec 8, 2024" },
  { title: "What's the Forecast?", passage: "Luke 12:54-59", series: "Luke", speaker: "Pastor Jon Bones", date: "Dec 1, 2024" },
  { title: "Jesus Gets Fired Up", passage: "Luke 12:49-53", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 24, 2024" },
  { title: "Ready for the Master's Return", passage: "Luke 12:35-48", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 17, 2024" },
  { title: "Worry Is Worthless", passage: "Luke 12:22-34", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 10, 2024" },
  { title: "Rich Toward God", passage: "Luke 12:13-21", series: "Luke", speaker: "Pastor Jon Bones", date: "Nov 3, 2024" },
  { title: "The Unpardonable Sin", passage: "Luke 12:1-12", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 27, 2024" },
  { title: "Lifting the Burden of Legalism", passage: "Luke 11:37-54", series: "Luke", speaker: "Pastor Jon Bones", date: "Oct 20, 2024" }
];
